### ISSUE TITLE
x.showbg() does not work in 2.0.0

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#863]
I can get the help for showbg, but I can't use it!

```
>>> import vcs, numpy as np
>>> x = vcs.init()
>>> i = np.identity(100)
>>> x.plot(i, bg=1)
<vcs.displayplot.Dp object at 0x2ad1288e4670>
>>> x.pdf('bgtest')
>>> x.showbg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/site-packages/vcs/Canvas.py", line 5212, in showbg
    a = apply(self.canvas.showbg, args)
AttributeError: 'module' object has no attribute 'showbg'
>>> help(x.showbg)
```
