### ISSUE TITLE
Building on OS X 10.10.2

### ISSUE THREAD

**Issue by jbeezley** [UV-CDAT/uvcdat#1012]
@aashish24 I think you said you were looking into this.  I found a particularly nasty problem you should be aware of.  I found that my builds have been generating thousands of crash reports like [this](https://gist.github.com/anonymous/ed7a64733073ce1be359).  

First, it looks like the `@cdat_osx_ld_flags@` shouldn't be [here](https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules_extra/cdat_common_environment.cmake.in#L2), but I don't think that is breaking anything.
However, `xcode-select` is crashing because our environment variables are loading an incompatible `libjpeg`.  If you use system `libjpg`, then it crashes like this:
```
dyld: Symbol not found: __cg_png_create_info_struct
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/jbeezley/build/uvcdat/b7aada3_mpi/install/Externals/lib/libPng.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Trace/BPT trap: 5
```

I will note that this is showing up as various configure problems.  For example. #1004 is likely caused by this (in my `CURL/config.log`):
```
configure:26438: ./conftest
dyld: Symbol not found: __cg_png_create_info_struct
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/jbeezley/build/uvcdat/b7aada3_mpi/install/Externals/lib/libPng.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
configure: line 2183: 73488 Trace/BPT trap: 5       ./conftest$ac_exeext
configure:26438: $? = 133
configure: program exited with status 133
```

As far as I can remember, this seems to be a recent problem.  I was building fine on 10.10 a couple of weeks ago.  Perhaps the system libraries were changed in the latest update.  I'm attempting to rebuild with jpg and png disabled.  I'll see how far down the rabbit hole this takes me.

**Comment by jbeezley** [comment]
I just got a successful default build by using system `libjpeg` and `libpng`.  Probably should make that a default when 10.10 is detected.

**Comment by potter2** [comment]
I would like to try to build on 10.10. When can you make the system  libjpeg and libpng default?

**Comment by doutriaux1** [comment]
@jbeezley does it actually run, I had a successful build as well (see my Yosemite branch) but then I had some runtime errors. If yours workcan you please push your changes to some branch we can review, tweak and merge? Thanks

**Comment by jbeezley** [comment]
Almost all of the tests passed.  I didn't actually make any changes to the code, I just configured like this:
```
cmake -DCDAT_USE_SYSTEM_PNG=ON -DCDAT_USE_SYSTEM_JPEG=ON -DCDAT_BUILD_PNG=OFF -DCDAT_BUILD_JPEG=OFF
```

I'm actually not sure how to detect OSX version 10.10 or how to make the above happen by default.  Maybe @aashish24 can help with that.

**Comment by aashish24** [comment]
We will look into fixing the issue with 10.10

**Comment by doutriaux1** [comment]
fix by https://github.com/UV-CDAT/uvcdat/pull/1110
